### ISSUE TITLE
error occurs when run test_block_mpc.py 

### ISSUE THREAD

**Issue by CreazeD** [Woodenonez/TrajTrack_MPCnDQN_RLBoost#1]
After I configured OpEn and the virtual environment, an error occurred when running the code. I don’t know what caused it, and there is very little information on the Internet.
![image](https://github.com/Woodenonez/TrajTrack_MPCnDQN_RLBoost/assets/132633595/47aaaf4e-e276-410c-8049-1cdf3020051c)

**Comment by Woodenonez** [comment]
Hi @CreazeD ,

Thank you for your interest.
This problem seems to be related to the OpEn package which is based on RUST. Since I haven't met this issue myself and we cannot provide much support on Windows OS right now, I can only provide some ideas to debug this.

If you go to opengen/builder/optimizer_builder.py, you can find functions called `__make_build_command` and `__build_optimizer`. The first one constructs a cargo command for the second one to build a solver. The error message suggests that the cargo build file is missing. This might be due to the misconfiguration of the environment variables. Ensure that any required environment variables are set correctly. The executable might be in a directory that is not included in the system's PATH.

Possible solutions include adding RUST into your system path (check [Configuring the PATH environment variable](https://www.rust-lang.org/tools/install)) or reinstalling RUST by carefully checking each step. If you have RUST correctly installed, you should be able to run `rustc --version` in your shell.

Hope it works :)

Best regards,
Ze
